export const cities = {
    select_city: [],
    Dhaka: [
      "100 Feet Road (Natun Bazar)",
      "60 feet Mor (Mirpur-2)",
      "Abdullahpur (Keraniganj)",
      "Adabor(Mohammadpur)",
      "Adam Ali Market(Mazar Road-Mirpur)",
      "Adamjee Cantonment College(Dhaka Cantonment)",
      "Adarsha Nagar (Middle Badda)",
      "Aftabnagar(Dhaka)",
      "Aga Nagar(Keraniganj)",
      "Agargaon(Dhaka)",
      "Ahalia-Uttara",
      "Ahmed Nagar-Paikpara(Mirpur-1)",
      "Ainusbag(Dakshinkhan)",
      "Ainusbag-Dakshinkhan",
      "Ajiz Market-ECB Chattar(Mirpur)",
      "Akran Bazar, Ashulia, Savar",
      "Alatunnessa School Road (South Badda)",
      "Alubazar (Puran Dhaka)",
      "Am Bagicha (Keraniganj)",
      "Amin Bazar, Savar",
      "Anayetpur Dhamrai",
      "Apollo Hospital (Bashundhara R/A)",
      "Arambag (Mirpur 7)",
      "Arambag (Motijheel)",
      "Arjotpara(Mohakhali)",
      "Armanitola (Puran Dhaka)",
      "Armed Forces Medical institute-MES",
      "Army housing Society(Dakshinkhan)",
      "Army officers Club(Dhaka Cantonment)",
      "Arshinagar (Keraniganj)",
      "Asad Avenue(Dhaka)",
      "Ashulia Thana, Baipayl, Savar",
      "Ashulia, Savar",
      "Askona(Dhaka)",
      "Atibazar (Keraniganj)",
      "Atipara(Dakshinkhan)",
      "Auchpara (Tongi collage Gate)",
      "Azimpur(Dhaka)",
      "Babli Masjid (Tejgoan)",
      "Babubazar (Puran Dhaka)",
      "Badam Toli (Babubazar)",
      "Badekomelosshor (Board Bazar)",
      "Badsha mia road (Demra)",
      "BAF Eagle hall(Dhaka Cantonment)",
      "BAF Shaheen College(Dhaka Cantonment)",
      "Bagbari (Dhaka)",
      "Baigertek-ECB(Mirpur)",
      "Baily Road (Dhaka)",
      "Baipail Dhamrai",
      "Baipayl Kacha Bazar, Ashulia, Savar",
      "Baipayl, Savar",
      "Bakshibazar (Puran Dhaka)",
      "Balughat Bazar Road(Mirpur)",
      "Balughat(Mirpur)",
      "Bamnartek(Uttara)",
      "Bamuail (Demra)",
      "Banani Block A",
      "Banani Block B",
      "Banani Block C",
      "Banani Block D",
      "Banani Block E",
      "Banani Block F",
      "Banani Block G",
      "Banani Block H",
      "Banani Block I",
      "Banani Block J",
      "Banani Block K",
      "Banani Block L",
      "Banani DOHS",
      "Banarupa Abashik(Khilkhet)",
      "Banasree Block - A (Dhaka)",
      "Banasree Block - B (Dhaka)",
      "Banasree Block - C (Dhaka)",
      "Banasree Block - D (Dhaka)",
      "Banasree Block - E (Dhaka)",
      "Banasree Block - F (Dhaka)",
      "Banasree Block - G (Dhaka)",
      "Banasree Block - H (Dhaka)",
      "Banasree Block - I (Dhaka)",
      "Banasree Block - J (Dhaka)",
      "Banasree Block - K (Dhaka)",
      "Banasree Block - L (Dhaka)",
      "Banasree Block - M (Dhaka)",
      "Banasree Block - N (Dhaka)",
      "Banasree(Dhaka)",
      "Bangla Bazar (Puran Dhaka)",
      "Bangla Motor(Dhaka)",
      "Bangladesh Army Headquerters(Dhaka Cantonment)",
      "Bangladesh Army headquerters(Dhaka Cantonment)",
      "Bangladesh University of Professionals(BUP)",
      "Baridhara Diplomatic Zone",
      "Baridhara DOHS",
    ],
    Gazipur: [
      "Bangla Bazar (Mawna)",
      "Awora khali (Kaliganj)",
      "Badhon (Pubail)",
      "Bagbari (Kashimpur)",
      "Bager bazar (Mawana-Gazipur)",
      "Baimail -Konabari (Gazipur)",
      "Barmi Sreepur (Gazipur)",
      "Barmi Sreepur (Sreepur)",
      "Baroipara (Kaliakoir)",
      "Bason Thana (Gazipur)",
      "Berenda (Kashimpur)",
      "Bhawal Government College (Gazipur)",
      "Bokhtarour (Kaliganj)",
      "Bolakar Mor (Maleker Bari)",
      "Boro Mosjid Road (Board Bazar)",
      "Borsha Hall (Gazipur Chowrasta)",
      "Bosuga (Pubail)",
      "Chondra (Kaliakoir)",
      "Chowrasta (Tongi)",
      "College gate (Pubail)",
      "Colombiya (Gazipur By Pass Road)",
      "Dalan bazar (Kaliganj)",
      "Dhaladia (Kapasia)",
      "Dhaladia Sreepur (Mawna Gazipur)",
      "Dhigir Chala (Gazipur Chowrasta)",
      "DUET (Joydebpur)",
      "Fulbaria bazar (Kaliakoir)",
      "Fuldi (Kaliganj)",
      "Gacha Bazar (Boro bari)",
      "Gacha Thana (Board Bazar)",
      "Gazipur Bypass",
      "Goalbari bazar (Kaliakoir)",
      "Gorgoria masterbari (Sreepur)",
      "Gorgoria Masterbari (Sreepur Gazipur)",
      "Great Wall Jame Masjid (Chandona Chowrasta)",
      "Hatimara-Kashimpur (Gazipur)",
      "Hoque Market (Gazipur By Pass Road)",
      "Hotapara (Mawan-Gazipur)",
      "Itahata (Chandona Chowrasta)",
      "IUT Road (Board Bazar)",
      "Jajhor (Board Bazar)",
      "Jalsukha -Baroipara (Kaliakoir)",
      "Jinumarket (Tongi Bus Stand)",
      "Jiter mor -Kashimpur (Gazipur)",
      "Jogitota (Joydebpur)",
      "Joina Bazar (Sreepur)",
      "Jorpukur (Joydebpur)",
      "Joyertek (Ambag Road-Konabari)",
      "Joyna Bazar (Sreepur Gazipur)",
      "Kabirpur (Kaliakoir)",
      "Kaliakoir Upazila (Gazipur)",
      "Kaliganj (Tongi)",
      "Kapasia (Gazipur)",
      "Kapasia Amraid (Kapasia)",
      "Kapasia Bazar (Kapasia)",
      "Kapasia Tok Noyon (Kapasia)",
      "Kashimpur Bazar (Gazipur)",
      "Kashimpur Bus Stop (Gazipur)",
      "Kashimpur Square (Gazipur)",
      "Kazi Market (Kashimpur)",
      "Kenakata Goli (Gazipur Chowrasta)",
      "Khapara (Hossain Market)",
      "Kodda (Gazipur By Pass Road road)",
      "Kodda Bazar (Tongi)",
      "Kodda bridge (Gazipur Chowrasta)",
      "Konabari (Gazipur)",
      "Konabari Bus stand (Gazipur)",
      "Konabari collage Gate (Gazipur)",
      "Konabari Jail khana (Gazipur)",
      "Konabari Kuddus Nagar (Gazipur)",
      "Madhobpur (Kashempur)",
      "Malakerbari (Tongi)",
      "Mawna Chowrasta",
      "Mc Bazar (Mawna)",
      "Member Bari (Mawna Gazipur)",
      "Miraspara (Tongi Bus stand)",
      "Mirerbazar (Tongi)",
      "Mirjapur Masterbari (Gazipur)",
      "Modhumita (Tongi Station Road)",
      "Mogor Khal (Gazipur By Pass Road)",
      "Molla market-(Kashimpur)",
      "Mollapara (Kashimpur)",
      "Mouchak (Gazipur)",
      "Mouchak Bazar (Kaliakair)",
      "Mudafa (Tongi cherag Ali)",
      "Mukter Bari Road (Board Bazar)",
      "Najor (Gazipur Chowrasta)",
      "Navanar Mor (Gazipur By Pass Road)",
      "Nawjor (Gazipur)",
      "Nayanpur Sreepur (Gazipur)",
      "Pagar - Miraspara (Tongi Bus Stand)",
      "Paler Math (Gazipur Chowrasta)",
      "Panishel (Kashimpur)",
      "Polagach Road (Board Bazar)",
      "Police Line (Gazipur Chowrasta)",
      "Pollibiddut-Konabari (Gazipur)",
      "Pollibidut (Chondra)",
      "Porabari Bazar (Gazipur)",
      "Porabari Bazar (Gazipur)",
      "Pubail (Tongi)",
      "Rail Gate (Tongi Station Road)",
      "Rajabari -Sreepur Road (Gazipur)",
      "Rajabari Sreepur (Gazipur)",
      "Rajendrapur Cantonment (Rajendrapur)",
      "Safari Park (Gazipur)",
      "Salna (Gazipur)",
      "Sardaganj-Kashimpur (Kaliakoir)",
      "Sattola Garments (Maleker Bari)",
      "Sawraid (Kaliganj)",
      "Shafipur (Kaliakoir-Gazipur)",
      "Shibbari (Joydebpur)",
      "Shilmun (Tongi Station Road)",
      "Shimultoli (Joydebpur)",
      "Shofipur Bus Stand (Kaliakair)",
      "Sorabo (Kashimpur)",
      "Sreepur Chowrasta (Mawna)",
      "Sultan Market - Kashimpur (Kaliakoir)",
      "Sultan Market Kashempur (Kaliakoir)",
      "Sultan Market (Kashimpur)",
      "T & T - (Tongi Station Road )",
      "Telipara (Chandona Chowrasta)",
      "Ulokhola (Kaliganj-Tongi)",
      "Vann",
    ],

    narayanganj: [
      "Araihazar Thana",
      "Baiddar Bazar (Sonargaon)",
      "Bandar (Modonpur)",
      "Bhuigor (Narayanganj)",
      "Bhulta (Rupganj)",
      "Chashara (Narayanganj)",
      "Chittagong Road (Narayanganj)",
      "Fatullah (Narayanganj)",
      "Jalkuri (Narayanganj)",
      "Kachpur (Modonpur Narayanganj)",
      "Modonganj (Bandar Naraynaganj)",
      "Modonpur Sadar (Modonpur)",
      "Morgapara (Sonargaon)",
      "Nabiganj (Bandar Narayanganj)",
      "Rupganj Thana",
      "Shanarpar (Narayanganj)",
      "Sibu market (Narayanganj)",
      "Siddhirganj (Narayanganj)",
      "Signboard (Narayanganj)",
      "Sonargaon (Narayanganj)",
    ],
    Faridpur: [
      "AKTER CHAR(Faridpur)",
      "Alfadanga",
      "ALGI(Faridpur)",
      "ALIABAD(Faridpur)",
      "AMBIKAPUR(Faridpur)",
      "AZIMNAGAR(Faridpur)",
      "Bhanga",
      "BHANGA(Faridpur)",
      "BHASHANCHAR(Faridpur)",
      "Boalmari",
      "CHANDRA(Faridpur)",
      "Char Bhadrasan",
      "CHAR BHADRASAN(Faridpur)",
      "CHAR BISHNUPUR(Faridpur)",
      "CHAR HARIRAMPUR(Faridpur)",
      "CHAR JASORDI(Faridpur)",
      "CHAR JHAUKANDA(Faridpur)",
      "CHAR MADHABDIA(Faridpur)",
      "CHAR MANAIR(Faridpur)",
      "CHAR NASIRPUR(Faridpur)",
      "CHUMORDI(Faridpur)",
      "DANGI(Faridpur)",
      "DECREERCHAR(Faridpur)",
      "DHEUKHALI(Faridpur)",
      "Faridpur Sadar",
      "FARIDPUR SADAR (Faridpur)",
      "GAZIRTEK(Faridpur)",
      "GHARUA(Faridpur)",
      "GREDA(Faridpur)",
      "HAMIRDI(Faridpur)",
      "ISHAN GOPALPUR(Faridpur)",
      "KAICHAIL(Faridpur)",
      "KAIJURI(Faridpur)",
      "KALAMRIDHA(Faridpur)",
      "KANAIPUR(Faridpur)",
      "KAOLIBERA(Faridpur)",
      "KODALIA SHOHIDNAGAR(Faridpur)",
      "KRISHNANAGAR(Faridpur)",
      "KRISHNAPUR(Faridpur)",
      "LASKARDIA(Faridpur)",
      "Madhukhali",
      "MAJCHAR(Faridpur)",
      "MANIKDAHA(Faridpur)",
      "Nagarkanda",
      "NAGARKANDA(Faridpur)",
      "NARIKELBARIA(Faridpur)",
      "NASIRABAD(Faridpur)",
      "NURULLAGANJ(Faridpur)",
      "Pathorghata(Barguna)",
      "PHULSUTI(Faridpur)",
      "PURA PARA(Faridpur)",
      "RAMNAGAR(Faridpur)",
      "Sadarpur",
      "SADARPUR(Faridpur)",
      "Saltha",
      "TALMA(Faridpur)",
      "TUZARPUR(Faridpur)",
      "UTTAR CHANNEL(Faridpur)",
    ],
    Gopalganj: [
      "Gopalganj Sadar",
      "Kasiani",
      "Kotalipara",
      "Maksudpur",  
      "Tungipara",
    ],
    Kishoreganj : [
      "Austogram",
      "Bajitpur",
      "Bhairab",
      "Hosainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kishoreganj Sadar",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
    Madaripur : [
  "2nd Nadirpar (Shibchar)",
  "Adompur (Madaripur Sadar)",
  "Ammgram Bridge (Rajoir)",
  "Angulkata Hat (Madaripur Sadar)",
  "Awaz (Madaripur Sadar)",
  "Baghmara(Shibchar)",
  "Bahadurpur ( Panch-char)",
  "Bakhorkandi (Shibchar)",
  "Banglabazar (Madaripur Sadar)",
  "Bhanga Bridge (Kalkini)",
  "Boiratola (Shibchar)",
  "Bolsha (Madaripur Sadar)",
  "Chagolchira (Rajoir)",
  "Chanderchar (Shibchar)",
  "Charmuguriya (Madaripur Sadar)",
  "Charnachna (Madaripur Sadar)",
  "Dasar (Kalkini)",
  "Dattopara (Shibchar)",
  "Faishatola (Kalkini)",
  "Fullbari (Rajoir)",
  "Gagonpur (kalkini)",
  "Ghatokchar (Madaripur Sadar)",
  "Ghosher Hat Chowrasta (Kalkini)",
  "Gopalpur (Kalkini)",
  "Habiganj (Madaripur Sadar)",
  "Hazrapur (Madaripur Sadar)",
  "Hossainer Hat (Shibchar)",
  "Housedi (Madaripur Sadar)",
  "Kabirajpur (Rajoir)",
  "Kadambari (Rajoir)",
  "Kadirpur (Shibchar)",
  "Kalabari (Rajoir)",
  "Kalagachiya (Rajoir)",
  "Kalikapur (Madaripur Sadar)",
  "Kalirbazar (Madaripur Sadar)",
  "Kalkini",
  "Kathalbari (Shibchar)",
  "Kawrakandi (Shibchar)",
  "Khagchora (Madaripur Sadar)",
  "Khagdi (Madaripur Sadar)",
  "Khaser Hat (Kalkini)",
  "Khaser hat (Shibchar)",
  "Khospur tekerhat (Madaripur Sadar)",
  "Kulpoddi Chowrsta (Madaripur Sadar)",
  "Kutubpur (Shibchar)",
  "Lakshmipur (Kalkini)",
  "Lokkhonda (Rajoir)",
  "Madaripur Launch Ghat (Madaripur Sadar)",
  "Madaripur Sadar",
  "Madaripur Sadar Thana (Madaripur Sadar)",
  "Madra (Kalkini)",
  "Maler Hat (Shibchar)",
  "Minara (Shibchar)",
  "Mithapur (Madaripur Sadar)",
  "Miyar Hat ( Kalkini)",
  "Mohisherchar Ferighat (Madaripur Sadar)",
  "Mollar Hat (Kalkini)",
  "Mostofapur (Madaripur Sadar)",
  "Munshirbazar (Shibchar)",
  "Nabogram (Kalkini)",
  "Naodoba (Shibchar)",
  "Nasirer Mor (Panch-Char)",
  "Nilokkhi (Rajoir)",
  "Notun Bus Stand (Madaripur Sadar)",
  "Pantapara (Rajoir)",
  "Pathuriyarpar (Kalkini)",
  "Puran Bazar (Madaripur Sadar)",
  "Rajoir",
  "Rajoir Bus Stand",
  "Ramjanpur (Kalkini)",
  "Shahebrampur ( Kalkini)",
  "Shakharpar (Rajoir)",
  "Sheikhpur (Shibchar)",
  "Shibchar",
  "Shimana (Shibchar)",
  "Shirkhara (Madaripur Sadar)",
  "Shomvuk (Shibchar)",
  "Sirail (Shibchar)",
  "Sreenadi (Madaripur Sadar)",
  "Surjonagar (Shibchar)",
  "Tekerhat (Rajoir)",
  "Uthrail (Shibchar)",
  "Vadroshan (Shichar)",
  "Vurghata (Kalkini)",
  "Yousufpur (Rajoir)",
    ],

    Manikganj : [  
    "Daulatpur(Manikganj)",
    "Ghior",
    "Harirampur (Manikganj)",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair",],
    Munshiganj : [
      "Alamin Bazar (Sreenagar)",
  "Baghra (Sreenagar)",
  "Baligaon (Munshiganj)",
  "Baluchar (Sirajdikhan)",
  "Bandura (Dohar)",
  "Baroykhali (Sreenagar)",
  "Bausia (Munshiganj)",
  "Boxsonagar (Nawabganj)",
  "Damla (Sreenagar)",
  "Dogachi Contonment (Sreenagar)",
  "Dohori (Munshiganj)",
  "Galimpur (Nawabganj)",
  "Gazaria (Munshiganj)",
  "Haridia (Louhajang)",
  "Holdia Bazar (Louhajang)",
  "Hossaindi (Munshiganj)",
  "Ichhapura Bazar (Sirajdikhan)",
  "Jamaldi (Munshiganj)",
  "Joypara (Dohar)",
  "Kacari (Munshiganj)",
  "Kartikpur (Dohar)",
  "Katakhali (Munshiganj)",
  "Kola (Sirajdikhan)",
  "Kolma (Munshiganj)",
  "Kuchiamora (Sirajdikhan)",
  "Kusumpur (Munshiganj)",
  "Lauhajang (Munshiganj)",
  "Loskorpur (Sreenagar)",
  "Malkhanagar (Sirajdikhan)",
  "Mawa (Louhajang)",
  "Mirkadim (Munshiganj)",
  "Muktarpur (Munshiganj)",
  "Munshir Hat (Munshiganj)",
  "Nawabganj Upazila",
  "Nimtola (Munshiganj)",
  "Rajanagar (Munshiganj)",
  "Rikabibazar (Munshiganj)",
  "Shekharnagar (Sreenagar)",
  "Singpara Bazar (Sirajdikhan)",
  "Sipahipara (Munshiganj)",
  "Sirajdikhan (Munshiganj)",
  "Sreenagar (Munshiganj)",
  "Super Market Mor (Munshiganj)",
  "Tangibari (Munshiganj)",
  "Tin Dokan (Sreenagar)",
  "Tontor (Sirajdikhan)",
  "Vaggokul (Sreenagar)",
  "Vaggyakul (Sreenagar)",
  "Voberchar (Munshiganj)",
    ],
Narsingdi  : [
  "Alamin Bazar (Sreenagar)",
  "Baghra (Sreenagar)",
  "Baligaon (Munshiganj)",
  "Baluchar (Sirajdikhan)",
  "Bandura (Dohar)",
  "Baroykhali (Sreenagar)",
  "Bausia (Munshiganj)",
  "Boxsonagar (Nawabganj)",
  "Damla (Sreenagar)",
  "Dogachi Contonment (Sreenagar)",
  "Dohori (Munshiganj)",
  "Galimpur (Nawabganj)",
  "Gazaria (Munshiganj)",
  "Haridia (Louhajang)",
  "Holdia Bazar (Louhajang)",
  "Hossaindi (Munshiganj)",
  "Ichhapura Bazar (Sirajdikhan)",
  "Jamaldi (Munshiganj)",
  "Joypara (Dohar)",
  "Kacari (Munshiganj)",
  "Kartikpur (Dohar)",
  "Katakhali (Munshiganj)",
  "Kola (Sirajdikhan)",
  "Kolma (Munshiganj)",
  "Kuchiamora (Sirajdikhan)",
  "Kusumpur (Munshiganj)",
  "Lauhajang (Munshiganj)",
  "Loskorpur (Sreenagar)",
  "Malkhanagar (Sirajdikhan)",
  "Mawa (Louhajang)",
  "Mirkadim (Munshiganj)",
  "Muktarpur (Munshiganj)",
  "Munshir Hat (Munshiganj)",
  "Nawabganj Upazila",
  "Nimtola (Munshiganj)",
  "Rajanagar (Munshiganj)",
  "Rikabibazar (Munshiganj)",
  "Shekharnagar (Sreenagar)",
  "Singpara Bazar (Sirajdikhan)",
  "Sipahipara (Munshiganj)",
  "Sirajdikhan (Munshiganj)",
  "Sreenagar (Munshiganj)",
  "Super Market Mor (Munshiganj)",
  "Tangibari (Munshiganj)",
  "Tin Dokan (Sreenagar)",
  "Tontor (Sirajdikhan)",
  "Vaggokul (Sreenagar)",
  "Vaggyakul (Sreenagar)",
  "Voberchar (Munshiganj)",
],
 Tangail : [
  "Bashail",
  "Bhuapur",
  "Delduar",
  "Dhalapara(Modhupur)",
  "Dhanbari(Modhupur)",
  "Garo Bazar(Modhupur)",
  "Ghatail Senanibash(Modhupur)",
  "Ghatail(Modhupur)",
  "Gopalpur (Tangail)",
  "Hamidpur(Modhupur)",
  "Jhorka(Modhupur)",
  "Kadomtoli(Modhupur)",
  "Kakraid(Modhupur)",
  "Kalihati",
  "Mirzapur",
  "Modhupur (Mymensingh)",
  "Nagarpur",
  "Sagordighi(Modhupur)",
  "Shakhipur",
  "Tangail Sadar",
],
 Shariatpur : [
  "Angaria (Shariatpur Sadar)",
  "Bhedarganj",
  "Binodpur (Shariatpur Sadar)",
  "Chikondi (Shariatpur Sadar)",
  "Chitoliya (Shariatpur Sadar)",
  "Damudiya",
  "Domshar (Shariatpur Sadar)",
  "Gosairhat",
  "Naria",
  "Palong (Shariatpur Sadar)",
  "Rudrokor (Shariatpur Sadar)",
  "Shakhipur (Shariatpur)",
  "Shariatpur Sadar",
  "Sholpara (Shariatpur Sadar)",
  "Tulasar (Shariatpur Sadar)",
  "Zajira",
],
 Rajbari : [
  "Alipur(Rajbari Sadar)",
  "Babupara(Pangsha Rajbari)",
  "Bahadurpur(Pangsha Rajbari)",
  "Baliakandi",
  "Baliakandi(Rajbari)",
  "Baniboho(Rajbari sadar)",
  "Boalia(Kalukhali Rajbari)",
  "Bohorpur(Baliakandi Rajbari)",
  "Borat((Rajbari Sadar)",
  "Bosontopur(Rajbari Sadar)",
  "Chandoni(Rajbari Sadar)",
  "Dadshi(Rajbari Sadar)",
  "Debgram(Goalondo Rajbari)",
  "Doulodia(Goalondo Rajbari)",
  "Goalunda",
  "Habashpur((Pangsha Rajbari)",
  "Islampur(Baliakandi Rajbari)",
  "Jamalpur(Baliakandi Rajbari)",
  "Jongol(Baliakandi Rajbari)",
  "Joshai(Pangsha Rajbari)",
  "Kalikapur(Kalukhali Rajbari)",
  "Kalukhali",
  "Khangong(Rajbari Sadar)",
  "Khankhanapur(Rajbari Sadar)",
  "Kolimohor(Pangsha Rajbari)",
  "Kosbamajail(Pangsha Rajbari)",
  "Majbari(Kalukhali Rajbari)",
  "Maspara(Pangsha Rajbari)",
  "Mijanpur(Rajbari Sadar)",
  "Modapur(Kalukhali Rajbari)",
  "Mourat(Pangsha Rajbari)",
  "Mrigi(Kalukhali Rajbari)",
  "Mulghor(Rajbari Sadar)",
  "Narua(Baliakandi Rajbari)",
  "Nobabpur(Baliakandi Rajbari)",
  "Pachuria(Rajbari Sadar)",
  "Pangsha",
  "Patta(Pangsha Rajbari)",
  "Rajbari Sadar",
  "Ramkantopur(Rajbari Sadar)",
  "Rotondia(Kalukhali Rajbari)",
  "Sahidohabpur(Rajbari Sadar)",
  "Shawrael(Kalukhali Rajbari)",
  "Sorisha(Pangsha Rajbari)",
  "Sotovakla(Goalondo Rajbari)",
  "Sultanpur(Rajbari Sadar)",
  "Ujanchor(Goalondo Rajbari)"
]};

 export const districtsOfBangladesh = [
    "Bagerhat",
    "Bandarban",
    "Barguna",
    "Barishal",
    "Bhola",
    "Bogura",
    "Brahmanbaria",
    "Chandpur",
    "Chattogram",
    "Chuadanga",
    "Comilla",
    "Cox's Bazar",
    "Dinajpur",
    "Feni",
    "Gaibandha",
    "Habiganj",
    "Jamalpur",
    "Jashore (Jessore)",
    "Jhalokathi",
    "Jhenaidah",
    "Joypurhat",
    "Khagrachari",
    "Khulna",
    "Kushtia",
    "Lakshmipur",
    "Lalmonirhat",
    "Magura",
    "Meherpur",
    "Moulvibazar",
    "Munshiganj",
    "Mymensingh",
    "Naogaon",
    "Narail",
    "Natore",
    "Netrokona",
    "Nilphamari",
    "Noakhali",
    "Pabna",
    "Panchagarh",
    "Patuakhali",
    "Pirojpur",
    "Rajbari",
    "Rajshahi",
    "Rangamati",
    "Rangpur",
    "Satkhira",
    "Sherpur",
    "Sirajganj",
    "Sunamganj",
    "Sylhet",
    "Tangail",
    "Thakurgaon",
    "Kurigram",
    "Natore",
  ];